import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img/>
          <a href='/'> Home</a>
          <a href='/events'> Events</a>
          <a href='/about-us'> About us</a>
        </nav>
      </header>
      <main className={styles.main}>
       <div>
        <img/>
        <h2>Events in London</h2>
        <p>
          this is a paragaph for the events in london
        </p>
       </div>
       <div>
        <img/>
        <h2>Events in Vancouver</h2>
        <p>
          this is a paragaph for the events in Vancouver
        </p>
       </div>
       <div>
        <img/>
        <h2>Events in Barcelona</h2>
        <p>
          this is a paragaph for the events in Barcelona
        </p>
       </div>
      </main>

      <footer className={styles.footer}>
        <p> 2023 3/2</p>
      </footer>
    </>
  )
}
