import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link legacyBehavior href="/" passHref>
            <a> Home</a>
          </Link>
          <Link legacyBehavior href="/events" passHref>
            <a> Events</a>
          </Link>
          <Link legacyBehavior href="/about-us" passHref>
            <a> About us</a>
          </Link>
        </nav>
      </header>
      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <p> 2023 3/2</p>
      </footer>
    </>
  );
}
// export async function getServerSideProps() {
//   const { events_categories } = await import("../../data/data.json");
//   return {
//     props: {
//       data: events_categories ,
//     },
//   };
// }
